/* eslint-disable @next/next/no-img-element */
import type { NextPage } from 'next';
import Head from 'next/head';
import { useCallback, useState } from 'react';
import { IoInfiniteOutline } from 'react-icons/io5';
import Counter from '../components/Counter/Counter';

const Home: NextPage = () => {
  const [picturesPaths, setPicturePaths] = useState([
    '/images/IMG_8206.jpeg',
    '/images/IMG_8226.jpg',
    '/images/IMG_8463.jpg',
    '/images/IMG_4272.jpeg',
  ]);

  const handleImageChange = useCallback(
    (position: number) => {
      const newArray = picturesPaths;

      newArray.push(picturesPaths[0]);
      newArray.splice(0, 1, picturesPaths[position]);
      newArray.splice(position, 1);

      setPicturePaths(() => [...newArray]);
    },
    [picturesPaths],
  );

  return (
    <div>
      <Head>
        <title>My Valentines</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="home">
        <div className="container">
          <div className="card img-card">
            <img className="img" src={picturesPaths[0]} alt="Picture of the author" />
          </div>

          <div className="card content-card text-center">
            {/* <img
              className="background-img"
              src={picturesPaths[0]}
              alt="Picture of the author"
            /> */}

            <div className="date">
              <p>14 de agosto de 2021</p>
              <p>17h, Topo do Mundo, Serra da Moeda. Brumadinho, MG</p>
            </div>

            <div className="divider">
              <div className="line"></div>
              <div className="px-4">
                <IoInfiniteOutline size={25} />
              </div>
              <div className="line"></div>
            </div>

            <div>
              <Counter />

              <div className="date text-end">
                <p>desde então...</p>
                {/* <IoHeartOutline size={25} /> */}
              </div>
            </div>

            <div className="divider">
              <div className="line"></div>
              <div className="px-4">
                <IoInfiniteOutline size={25} />
              </div>
              <div className="line"></div>
            </div>

            <div className="pictures">
              <div
                role="button"
                className="picture-container"
                onClick={() => handleImageChange(1)}
              >
                <img
                  className="picture"
                  src={picturesPaths[1]}
                  alt="Picture of the author"
                />
              </div>

              <div
                role="button"
                className="picture-container"
                onClick={() => handleImageChange(2)}
              >
                <img
                  className="picture"
                  src={picturesPaths[2]}
                  alt="Picture of the author"
                />
              </div>

              <div
                role="button"
                className="picture-container"
                onClick={() => handleImageChange(3)}
              >
                <img
                  className="picture"
                  src={picturesPaths[3]}
                  alt="Picture of the author"
                />
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
