/* eslint-disable @next/next/no-img-element */
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { DateTime, Duration, DurationUnits } from 'luxon';
import { IoInfiniteOutline, IoHeartOutline } from 'react-icons/io5';

import { Container } from './styles';

const units: DurationUnits = [
  'years',
  'months',
  'days',
  'hours',
  'minutes',
  'seconds',
  'milliseconds',
];

const Home: NextPage = () => {
  const [picturesPaths, setPicturePaths] = useState([
    '/images/IMG_8206.jpeg',
    '/images/IMG_8226.jpg',
    '/images/IMG_8463.jpg',
    '/images/IMG_4272.jpeg',
  ]);

  const startDate = DateTime.fromISO('2021-08-14T17:30');

  const [diff, setDiff] = useState<Duration>(DateTime.now().diff(startDate, units));
  const [selectedImg, setSelectedImg] = useState(picturesPaths[0]);

  useEffect(() => {
    setInterval(() => {
      const diff = DateTime.now().diff(startDate, units);
      setDiff(diff);
    }, 1000);
  }, [startDate]);

  const handleImageChange = (position: number) => {
    setSelectedImg(picturesPaths[position]);

    const newArray = picturesPaths;

    newArray.push(picturesPaths[0]);
    newArray.splice(0, 1, picturesPaths[position]);
    newArray.splice(position, 1);

    setPicturePaths(newArray);
  };

  const format = (num: number) => {
    return num > 9 ? '' + num : '0' + num;
  };

  return (
    <div>
      <Head>
        <title>My Valentines</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <div className="container">
          <div className="card img-card">
            <img className="img" src={selectedImg} alt="Picture of the author" />
          </div>

          <div className="card content-card text-center">
            <div className="date pb-4">
              <p>14 de agosto de 2021</p>
              <p>17h, Topo do Mundo, Serra da Moeda. Brumadinho, MG</p>
            </div>

            <div className="divider">
              <div className="line"></div>
              <div className="px-4">
                <IoInfiniteOutline size={25} />
              </div>
              <div className="line"></div>
            </div>

            <div className="py-4">
              <div className="counter-container">
                <div className="timer-container">
                  <h4 className="timer">{format(diff?.years)}</h4>
                  <span className="unit"> Anos</span>
                </div>

                <div className="timer-container">
                  <h4 className="timer">{format(diff?.months)}</h4>
                  <span className="unit"> Meses</span>
                </div>

                <div className="timer-container">
                  <h4 className="timer">{format(diff?.days)}</h4>
                  <span className="unit"> Dias</span>
                </div>

                <div className="timer-container">
                  <h4 className="timer">{format(diff?.hours)}</h4>
                  <span className="unit"> Horas</span>
                </div>

                <div className="timer-container">
                  <h4 className="timer">{format(diff?.seconds)}</h4>
                  <span className="unit"> Segundos</span>
                </div>
              </div>

              <div className="date">
                <p>Desde então</p>
                <IoHeartOutline size={25} />
              </div>
            </div>

            <div className="divider">
              <div className="line"></div>
              <div className="px-4">
                <IoInfiniteOutline size={25} />
              </div>
              <div className="line"></div>
            </div>

            <div className="pictures pt-4">
              <div
                role="button"
                className="picture-container"
                onClick={() => handleImageChange(1)}
              >
                <img
                  className="picture"
                  src={picturesPaths[1]}
                  alt="Picture of the author"
                />
              </div>

              <div
                role="button"
                className="picture-container"
                onClick={() => handleImageChange(2)}
              >
                <img
                  className="picture"
                  src={picturesPaths[2]}
                  alt="Picture of the author"
                />
              </div>

              <div
                role="button"
                className="picture-container"
                onClick={() => handleImageChange(3)}
              >
                <img
                  className="picture"
                  src={picturesPaths[3]}
                  alt="Picture of the author"
                />
              </div>
            </div>
          </div>
        </div>
      </Container>
    </div>
  );
};

export default Home;
